//! [`wide`] vector types as [`Simd`] backends.
//!
//! `wide` is pure Rust over `safe_arch`, so enabling the backend adds no C
//! and no build script. On x86-64 with AVX-512 its `f64x8` is a native
//! `__m512d`; without it, `wide` composes narrower registers, and the kernels
//! are unaffected either way.
//!
//! The three widths are generated by one macro because their APIs are
//! identical — which is the point: adding a width is a single line, not a
//! third copy of every kernel.

use super::{Mask, Simd};

macro_rules! impl_wide {
    ($vec:ty, $lanes:literal) => {
        impl Mask for MaskOf<$vec> {
            const LANES: usize = $lanes;
            type Bools = [bool; $lanes];

            #[inline(always)]
            fn any(self) -> bool {
                self.0.any()
            }
            #[inline(always)]
            fn all(self) -> bool {
                self.0.all()
            }
            #[inline(always)]
            fn and(self, other: Self) -> Self {
                MaskOf(self.0 & other.0)
            }
            #[inline(always)]
            fn or(self, other: Self) -> Self {
                MaskOf(self.0 | other.0)
            }
            #[inline(always)]
            fn not(self) -> Self {
                // A `wide` comparison yields all-ones or all-zeros per lane,
                // so negation is a select between those two patterns. Done
                // this way rather than with `!`, which `wide` does not provide
                // for float vectors.
                MaskOf(self.0.select(<$vec>::ZERO, ALL_ONES_.0))
            }
            #[inline(always)]
            fn to_bools(self) -> Self::Bools {
                let lanes: [f64; $lanes] = self.0.into();
                lanes.map(|v| v.to_bits() != 0)
            }
        }

        impl Simd for $vec {
            const LANES: usize = $lanes;
            type Mask = MaskOf<$vec>;
            type Floats = [f64; $lanes];
            type Bits = [u64; $lanes];
            type Bools = [bool; $lanes];

            #[inline(always)]
            fn splat(v: f64) -> Self {
                <$vec>::splat(v)
            }
            #[inline(always)]
            fn to_array(self) -> Self::Floats {
                self.into()
            }
            #[inline(always)]
            fn from_array(a: Self::Floats) -> Self {
                <$vec>::new(a)
            }
            #[inline(always)]
            fn to_bits(self) -> Self::Bits {
                let lanes: [f64; $lanes] = self.into();
                lanes.map(f64::to_bits)
            }
            #[inline(always)]
            fn from_bits(b: Self::Bits) -> Self {
                <$vec>::new(b.map(f64::from_bits))
            }

            #[inline(always)]
            fn mul_add(self, mul: Self, add: Self) -> Self {
                // `wide` silently degrades `mul_add` to `self * mul + add`
                // when the target has no FMA — two roundings where the
                // contract requires one. That is not a small difference: it
                // costs bit-exactness on roughly one input in two thousand,
                // which is precisely the kind of failure that survives casual
                // testing. Fall back to a genuine per-lane FMA instead, which
                // is slower but correct; build with `-C target-cpu=native` (or
                // `-C target-feature=+fma`) to get the vector instruction.
                #[cfg(target_feature = "fma")]
                {
                    <$vec>::mul_add(self, mul, add)
                }
                #[cfg(not(target_feature = "fma"))]
                {
                    let a: [f64; $lanes] = self.into();
                    let b: [f64; $lanes] = mul.into();
                    let c: [f64; $lanes] = add.into();
                    let mut out = [0.0f64; $lanes];
                    for i in 0..$lanes {
                        out[i] = a[i].mul_add(b[i], c[i]);
                    }
                    <$vec>::new(out)
                }
            }
            #[inline(always)]
            fn abs(self) -> Self {
                <$vec>::abs(self)
            }
            #[inline(always)]
            fn sqrt(self) -> Self {
                <$vec>::sqrt(self)
            }

            #[inline(always)]
            fn lt_mask(self, other: Self) -> Self::Mask {
                MaskOf(self.simd_lt(other))
            }
            #[inline(always)]
            fn le_mask(self, other: Self) -> Self::Mask {
                MaskOf(self.simd_le(other))
            }
            #[inline(always)]
            fn gt_mask(self, other: Self) -> Self::Mask {
                MaskOf(self.simd_gt(other))
            }
            #[inline(always)]
            fn ge_mask(self, other: Self) -> Self::Mask {
                MaskOf(self.simd_ge(other))
            }
            #[inline(always)]
            fn eq_mask(self, other: Self) -> Self::Mask {
                MaskOf(self.simd_eq(other))
            }

            #[inline(always)]
            fn select(mask: Self::Mask, if_true: Self, if_false: Self) -> Self {
                mask.0.select(if_true, if_false)
            }
        }
    };
}

/// A comparison result.
///
/// A newtype rather than the bare vector: in `wide` a mask *is* an `f64xN`
/// whose lanes are all-ones or all-zeros, so without this the `Mask` and
/// `Simd` impls would collide on the same type.
#[derive(Clone, Copy, Debug)]
pub struct MaskOf<V>(pub V);

macro_rules! all_ones {
    ($vec:ty, $lanes:literal) => {
        const ALL_ONES_: MaskOf<$vec> = MaskOf(<$vec>::new([f64::from_bits(u64::MAX); $lanes]));
    };
}

mod x2 {
    use super::*;
    use wide::f64x2;
    all_ones!(f64x2, 2);
    impl_wide!(f64x2, 2);
}

mod x4 {
    use super::*;
    use wide::f64x4;
    all_ones!(f64x4, 4);
    impl_wide!(f64x4, 4);
}

mod x8 {
    use super::*;
    use wide::f64x8;
    all_ones!(f64x8, 8);
    impl_wide!(f64x8, 8);
}
