//! [`wide`] vector types as [`Simd`] backends.
//!
//! `wide` is pure Rust over `safe_arch`, so enabling the backend adds no C
//! and no build script. On x86-64 with AVX-512 its `f64x8` is a native
//! `__m512d` and its `f32x16` a native `__m512`; without it, `wide` composes
//! narrower registers, and the kernels are unaffected either way.
//!
//! The six widths — three per precision, at 128, 256 and 512 bits — are
//! generated by one macro because their APIs are identical, which is the
//! point: adding a width is a single line, not another copy of every kernel.

use super::{Mask, Simd};

macro_rules! impl_wide {
    ($vec:ty, $elem:ty, $uint:ty, $lanes:literal, $wide:ty) => {
        impl Mask for MaskOf<$vec> {
            const LANES: usize = $lanes;
            type Bools = [bool; $lanes];

            #[inline(always)]
            fn any(self) -> bool {
                self.0.any()
            }
            #[inline(always)]
            fn all(self) -> bool {
                self.0.all()
            }
            #[inline(always)]
            fn and(self, other: Self) -> Self {
                MaskOf(self.0 & other.0)
            }
            #[inline(always)]
            fn or(self, other: Self) -> Self {
                MaskOf(self.0 | other.0)
            }
            #[inline(always)]
            fn not(self) -> Self {
                // A `wide` comparison yields all-ones or all-zeros per lane,
                // so negation is a select between those two patterns. Done
                // this way rather than with `!`, which `wide` does not provide
                // for float vectors.
                MaskOf(self.0.select(<$vec>::ZERO, ALL_ONES_.0))
            }
            #[inline(always)]
            fn to_bools(self) -> Self::Bools {
                let lanes: [$elem; $lanes] = self.0.into();
                lanes.map(|v| v.to_bits() != 0)
            }
        }

        impl Simd for $vec {
            type Elem = $elem;
            const LANES: usize = $lanes;
            type Mask = MaskOf<$vec>;
            type Floats = [$elem; $lanes];
            type Bits = [$uint; $lanes];
            type Bools = [bool; $lanes];
            type Wide = $wide;

            #[inline(always)]
            fn widen(self) -> $wide {
                // Via the lane array rather than a dedicated intrinsic: `wide`
                // exposes no widening conversion, and this lowers to the same
                // single `cvtps2pd` — the loop is fixed-length and every lane
                // is independent.
                let lanes: [$elem; $lanes] = self.into();
                <$wide>::new(lanes.map(|v| v as f64))
            }
            #[inline(always)]
            fn narrow(wide: $wide) -> Self {
                let lanes: [f64; $lanes] = wide.into();
                <$vec>::new(lanes.map(|v| v as $elem))
            }

            #[inline(always)]
            fn splat(v: $elem) -> Self {
                <$vec>::splat(v)
            }
            #[inline(always)]
            fn to_array(self) -> Self::Floats {
                self.into()
            }
            #[inline(always)]
            fn from_array(a: Self::Floats) -> Self {
                <$vec>::new(a)
            }
            #[inline(always)]
            fn to_bits(self) -> Self::Bits {
                let lanes: [$elem; $lanes] = self.into();
                lanes.map(<$elem>::to_bits)
            }
            #[inline(always)]
            fn from_bits(b: Self::Bits) -> Self {
                <$vec>::new(b.map(<$elem>::from_bits))
            }

            #[inline(always)]
            fn mul_add(self, mul: Self, add: Self) -> Self {
                // `wide` silently degrades `mul_add` to `self * mul + add`
                // when the target has no FMA — two roundings where the
                // contract requires one. That is not a small difference: it
                // costs bit-exactness on roughly one input in two thousand,
                // which is precisely the kind of failure that survives casual
                // testing. Fall back to a genuine per-lane FMA instead, which
                // is slower but correct; build with `-C target-cpu=native` (or
                // `-C target-feature=+fma`) to get the vector instruction.
                #[cfg(target_feature = "fma")]
                {
                    <$vec>::mul_add(self, mul, add)
                }
                #[cfg(not(target_feature = "fma"))]
                {
                    let a: [$elem; $lanes] = self.into();
                    let b: [$elem; $lanes] = mul.into();
                    let c: [$elem; $lanes] = add.into();
                    let mut out = [0.0 as $elem; $lanes];
                    for i in 0..$lanes {
                        out[i] = a[i].mul_add(b[i], c[i]);
                    }
                    <$vec>::new(out)
                }
            }
            #[inline(always)]
            fn abs(self) -> Self {
                <$vec>::abs(self)
            }
            #[inline(always)]
            fn sqrt(self) -> Self {
                <$vec>::sqrt(self)
            }

            #[inline(always)]
            fn floor(self) -> Self {
                <$vec>::floor(self)
            }
            #[inline(always)]
            fn ceil(self) -> Self {
                <$vec>::ceil(self)
            }
            #[inline(always)]
            fn trunc(self) -> Self {
                <$vec>::trunc(self)
            }
            #[inline(always)]
            fn round_ties_even(self) -> Self {
                <$vec>::round_ties_even(self)
            }

            #[inline(always)]
            fn and_bits(self, other: Self) -> Self {
                self & other
            }
            #[inline(always)]
            fn or_bits(self, other: Self) -> Self {
                self | other
            }
            #[inline(always)]
            fn xor_bits(self, other: Self) -> Self {
                self ^ other
            }

            #[inline(always)]
            fn lt_mask(self, other: Self) -> Self::Mask {
                MaskOf(self.simd_lt(other))
            }
            #[inline(always)]
            fn le_mask(self, other: Self) -> Self::Mask {
                MaskOf(self.simd_le(other))
            }
            #[inline(always)]
            fn gt_mask(self, other: Self) -> Self::Mask {
                MaskOf(self.simd_gt(other))
            }
            #[inline(always)]
            fn ge_mask(self, other: Self) -> Self::Mask {
                MaskOf(self.simd_ge(other))
            }
            #[inline(always)]
            fn eq_mask(self, other: Self) -> Self::Mask {
                MaskOf(self.simd_eq(other))
            }

            #[inline(always)]
            fn select(mask: Self::Mask, if_true: Self, if_false: Self) -> Self {
                mask.0.select(if_true, if_false)
            }
        }
    };
}

/// A comparison result.
///
/// A newtype rather than the bare vector: in `wide` a mask *is* an `fNxM`
/// whose lanes are all-ones or all-zeros, so without this the `Mask` and
/// `Simd` impls would collide on the same type.
#[derive(Clone, Copy, Debug)]
pub struct MaskOf<V>(pub V);

macro_rules! all_ones {
    ($vec:ty, $elem:ty, $uint:ty, $lanes:literal) => {
        const ALL_ONES_: MaskOf<$vec> =
            MaskOf(<$vec>::new([<$elem>::from_bits(<$uint>::MAX); $lanes]));
    };
}

macro_rules! backend {
    ($modname:ident, $vec:ident, $elem:ty, $uint:ty, $lanes:literal, $wide:ident) => {
        mod $modname {
            use super::*;
            use wide::{$vec, $wide};
            all_ones!($vec, $elem, $uint, $lanes);
            impl_wide!($vec, $elem, $uint, $lanes, $wide);
        }
    };
    // A double-precision width is its own widening.
    ($modname:ident, $vec:ident, $lanes:literal) => {
        mod $modname {
            use super::*;
            use wide::$vec;
            all_ones!($vec, f64, u64, $lanes);
            impl_wide!($vec, f64, u64, $lanes, $vec);
        }
    };
}

backend!(d2, f64x2, 2);
backend!(d4, f64x4, 4);
backend!(d8, f64x8, 8);
backend!(s4, f32x4, f32, u32, 4, f64x4);
backend!(s8, f32x8, f32, u32, 8, f64x8);

// `f32x16` is deliberately absent. Every single-precision kernel that has to
// be bit-exact replays the platform routine's *double-precision* schedule —
// that is what `expf`, `logf`, `sinf` and `powf` actually do — so a width is
// only usable if the matching `f64xN` exists to widen into, and `wide` stops
// at `f64x8`.
