//! Shared `expf` / `exp2f` / `powf` data: the 32-entry 2^(i/32) table.
//!
//! GENERATED by `tools/gen_tables.py` — do not edit by hand.
//!
//! Transcribed from ARM optimized-routines `math/exp2f_data.c` (N = 32),
//! Copyright (c) 2017-2024 Arm Limited, SPDX-License-Identifier:
//! `MIT OR Apache-2.0 WITH LLVM-exception`. Byte-identical to the table glibc
//! compiles into `__expf` / `__exp2f` / `__powf`.
//!
//! Every constant here is an `f64`, and deliberately so: the single-precision
//! routines evaluate in double precision and round once at the end. See
//! [`crate::kernels::single`].
//!
//! Values are exact bit patterns; the trailing comment is the upstream
//! hex-float spelling.

/// `exp2f`'s rounding constant, `0x1.8p52 / N`.
/// Upstream: `0x1.8p+52 / N`.
pub const SHIFT_SCALED: f64 = f64::from_bits(0x42e8000000000000);

/// The round-to-nearest-integer trick constant, `0x1.8p52`.
/// Upstream: `0x1.8p+52`.
pub const SHIFT: f64 = f64::from_bits(0x4338000000000000);

/// `N / ln(2)`, `expf`'s reduction scale.
/// Upstream: `0x1.71547652b82fep+0 * N`.
pub const INVLN2_SCALED: f64 = f64::from_bits(0x40471547652b82fe);

/// `exp2f` coefficients for `2^r - 1` on `|r| < 1/64`, in the order the
/// kernel consumes them: `C[0] r^3 + C[1] r^2 + C[2] r + 1`.
/// Upstream: `0x1.c6af84b912394p-5`.
pub const C0: f64 = f64::from_bits(0x3fac6af84b912394);
/// Upstream: `0x1.ebfce50fac4f3p-3`.
pub const C1: f64 = f64::from_bits(0x3fcebfce50fac4f3);
/// Upstream: `0x1.62e42ff0c52d6p-1`.
pub const C2: f64 = f64::from_bits(0x3fe62e42ff0c52d6);

/// The same coefficients pre-divided by powers of `N`, for `expf`,
/// whose reduced argument is `N` times larger.
/// Upstream: `0x1.c6af84b912394p-20`.
pub const CS0: f64 = f64::from_bits(0x3ebc6af84b912394);
/// Upstream: `0x1.ebfce50fac4f3p-13`.
pub const CS1: f64 = f64::from_bits(0x3f2ebfce50fac4f3);
/// Upstream: `0x1.62e42ff0c52d6p-6`.
pub const CS2: f64 = f64::from_bits(0x3f962e42ff0c52d6);

/// `2^(i/32)` for `i` in `0..32`, with the exponent pre-subtracted so
/// that adding `ki << (52 - 5)` reconstructs the scale with one
/// integer add.
pub static TAB: [u64; 32] = [
    0x3ff0000000000000,
    0x3fefd9b0d3158574,
    0x3fefb5586cf9890f,
    0x3fef9301d0125b51,
    0x3fef72b83c7d517b,
    0x3fef54873168b9aa,
    0x3fef387a6e756238,
    0x3fef1e9df51fdee1,
    0x3fef06fe0a31b715,
    0x3feef1a7373aa9cb,
    0x3feedea64c123422,
    0x3feece086061892d,
    0x3feebfdad5362a27,
    0x3feeb42b569d4f82,
    0x3feeab07dd485429,
    0x3feea47eb03a5585,
    0x3feea09e667f3bcd,
    0x3fee9f75e8ec5f74,
    0x3feea11473eb0187,
    0x3feea589994cce13,
    0x3feeace5422aa0db,
    0x3feeb737b0cdc5e5,
    0x3feec49182a3f090,
    0x3feed503b23e255d,
    0x3feee89f995ad3ad,
    0x3feeff76f2fb5e47,
    0x3fef199bdd85529c,
    0x3fef3720dcef9069,
    0x3fef5818dcfba487,
    0x3fef7c97337b9b5f,
    0x3fefa4afa2a490da,
    0x3fefd0765b6e4540,
];
