//! `exp10f` data: the one reduction constant that is not already `exp2f`'s.
//!
//! GENERATED by `tools/gen_tables.py` — do not edit by hand.
//!
//! Transcribed from glibc's `sysdeps/ieee754/flt-32/e_exp10f.c`. The 32-entry
//! `2^(i/32)` table and the three scaled polynomial coefficients are
//! `__exp2f_data`'s, which [`super::exp`] already holds — `exp10f` is `exp2f`
//! with a different reduction scale and nothing else — so only the scale
//! itself lives here.
//!
//! Values are exact bit patterns; the trailing comment is the upstream
//! hex-float spelling, `N = 32`.

/// `N * log2(10)`. Argument reduction scale: `k = round(x * INVLN10N)`.
/// Upstream: `0x3.5269e12f346e2p0 * N`.
pub const INVLN10N: f64 = f64::from_bits(0x405a934f0979a371);

/// The largest `f32` with `10^x < 2^128`; above it `exp10f` overflows.
/// Upstream: `0x26.8826ap0f`.
pub const OFLOW_BOUND: f32 = f32::from_bits(0x421a209a);

/// The smallest `f32` with `10^x > 2^-150`; below it `exp10f` is zero.
/// Upstream: `-0x2d.278d4p0f`.
pub const UFLOW_BOUND: f32 = f32::from_bits(0xc2349e35);

/// `top13(38.0f)`, where the scalar routine leaves its main path.
pub const BIG_TOP13: u32 = 0x843;

/// `top13(INFINITY)`.
pub const INF_TOP13: u32 = 0xff0;

/// `log2(10)` in `f32`, for the table-free path.
pub const LOG2_10: f32 = f32::from_bits(0x40549a78);

/// `log10(2)`, high part, with enough low significand bits cleared that
/// `kd * LOG10_2HI` is exact for every `|kd| < 256` the reduction produces.
pub const LOG10_2HI: f32 = f32::from_bits(0x3e9a2000);

/// `log10(2) - LOG10_2HI`, to `f32`. See [`LOG10_2HI`].
pub const LOG10_2LO: f32 = f32::from_bits(0x369a84fc);
