//! `logf` / `log10f` data: the 16-subinterval table.
//!
//! GENERATED by `tools/gen_tables.py` — do not edit by hand.
//!
//! Transcribed from ARM optimized-routines `math/logf_data.c` (N = 16),
//! Copyright (c) 2017-2024 Arm Limited, SPDX-License-Identifier:
//! `MIT OR Apache-2.0 WITH LLVM-exception`. Byte-identical to the table glibc
//! compiles into `__logf`.
//!
//! Every constant here is an `f64`, and deliberately so: the single-precision
//! routines evaluate in double precision and round once at the end. See
//! [`crate::kernels::single`].
//!
//! Values are exact bit patterns; the trailing comment is the upstream
//! hex-float spelling.

/// ln(2).
/// Upstream: `0x1.62e42fefa39efp-1`.
pub const LN2: f64 = f64::from_bits(0x3fe62e42fefa39ef);

/// 1 / ln(10), for `log10f`.
/// Upstream: `0x1.bcb7b1526e50ep-2`.
pub const INVLN10: f64 = f64::from_bits(0x3fdbcb7b1526e50e);

/// Polynomial coefficients, in the order the kernel consumes them.
/// Upstream: `-0x1.00ea348b88334p-2`.
pub const A0: f64 = f64::from_bits(0xbfd00ea348b88334);
/// Upstream: `0x1.5575b0be00b6ap-2`.
pub const A1: f64 = f64::from_bits(0x3fd5575b0be00b6a);
/// Upstream: `-0x1.ffffef20a4123p-2`.
pub const A2: f64 = f64::from_bits(0xbfdffffef20a4123);

/// `[invc, logc]` interleaved for each subinterval: `TAB[2i] = 1/c`
/// and `TAB[2i+1] = log(c)` (log2 for the `log2f` and `powf` tables),
/// with `c` near the centre of subinterval `i`.
pub static TAB: [f64; 32] = [
    f64::from_bits(0x3ff661ec79f8f3be),
    f64::from_bits(0xbfd57bf7808caade), // 0
    f64::from_bits(0x3ff571ed4aaf883d),
    f64::from_bits(0xbfd2bef0a7c06ddb), // 1
    f64::from_bits(0x3ff49539f0f010b0),
    f64::from_bits(0xbfd01eae7f513a67), // 2
    f64::from_bits(0x3ff3c995b0b80385),
    f64::from_bits(0xbfcb31d8a68224e9), // 3
    f64::from_bits(0x3ff30d190c8864a5),
    f64::from_bits(0xbfc6574f0ac07758), // 4
    f64::from_bits(0x3ff25e227b0b8ea0),
    f64::from_bits(0xbfc1aa2bc79c8100), // 5
    f64::from_bits(0x3ff1bb4a4a1a343f),
    f64::from_bits(0xbfba4e76ce8c0e5e), // 6
    f64::from_bits(0x3ff12358f08ae5ba),
    f64::from_bits(0xbfb1973c5a611ccc), // 7
    f64::from_bits(0x3ff0953f419900a7),
    f64::from_bits(0xbfa252f438e10c1e), // 8
    f64::from_bits(0x3ff0000000000000),
    f64::from_bits(0x0000000000000000), // 9
    f64::from_bits(0x3fee608cfd9a47ac),
    f64::from_bits(0x3faaa5aa5df25984), // 10
    f64::from_bits(0x3feca4b31f026aa0),
    f64::from_bits(0x3fbc5e53aa362eb4), // 11
    f64::from_bits(0x3feb2036576afce6),
    f64::from_bits(0x3fc526e57720db08), // 12
    f64::from_bits(0x3fe9c2d163a1aa2d),
    f64::from_bits(0x3fcbc2860d224770), // 13
    f64::from_bits(0x3fe886e6037841ed),
    f64::from_bits(0x3fd1058bc8a07ee1), // 14
    f64::from_bits(0x3fe767dcf5534862),
    f64::from_bits(0x3fd4043057b6ee09), // 15
];
