//! `log2f` data: the 16-subinterval table.
//!
//! GENERATED by `tools/gen_tables.py` — do not edit by hand.
//!
//! Transcribed from ARM optimized-routines `math/log2f_data.c` (N = 16),
//! Copyright (c) 2017-2024 Arm Limited, SPDX-License-Identifier:
//! `MIT OR Apache-2.0 WITH LLVM-exception`. Byte-identical to the table glibc
//! compiles into `__log2f`.
//!
//! Every constant here is an `f64`, and deliberately so: the single-precision
//! routines evaluate in double precision and round once at the end. See
//! [`crate::kernels::single`].
//!
//! Values are exact bit patterns; the trailing comment is the upstream
//! hex-float spelling.

/// Polynomial coefficients, in the order the kernel consumes them.
/// Upstream: `-0x1.712b6f70a7e4dp-2`.
pub const A0: f64 = f64::from_bits(0xbfd712b6f70a7e4d);
/// Upstream: `0x1.ecabf496832e0p-2`.
pub const A1: f64 = f64::from_bits(0x3fdecabf496832e0);
/// Upstream: `-0x1.715479ffae3dep-1`.
pub const A2: f64 = f64::from_bits(0xbfe715479ffae3de);
/// Upstream: `0x1.715475f35c8b8p+0`.
pub const A3: f64 = f64::from_bits(0x3ff715475f35c8b8);

/// `[invc, logc]` interleaved for each subinterval: `TAB[2i] = 1/c`
/// and `TAB[2i+1] = log(c)` (log2 for the `log2f` and `powf` tables),
/// with `c` near the centre of subinterval `i`.
pub static TAB: [f64; 32] = [
    f64::from_bits(0x3ff661ec79f8f3be),
    f64::from_bits(0xbfdefec65b963019), // 0
    f64::from_bits(0x3ff571ed4aaf883d),
    f64::from_bits(0xbfdb0b6832d4fca4), // 1
    f64::from_bits(0x3ff49539f0f010b0),
    f64::from_bits(0xbfd7418b0a1fb77b), // 2
    f64::from_bits(0x3ff3c995b0b80385),
    f64::from_bits(0xbfd39de91a6dcf7b), // 3
    f64::from_bits(0x3ff30d190c8864a5),
    f64::from_bits(0xbfd01d9bf3f2b631), // 4
    f64::from_bits(0x3ff25e227b0b8ea0),
    f64::from_bits(0xbfc97c1d1b3b7af0), // 5
    f64::from_bits(0x3ff1bb4a4a1a343f),
    f64::from_bits(0xbfc2f9e393af3c9f), // 6
    f64::from_bits(0x3ff12358f08ae5ba),
    f64::from_bits(0xbfb960cbbf788d5c), // 7
    f64::from_bits(0x3ff0953f419900a7),
    f64::from_bits(0xbfaa6f9db6475fce), // 8
    f64::from_bits(0x3ff0000000000000),
    f64::from_bits(0x0000000000000000), // 9
    f64::from_bits(0x3fee608cfd9a47ac),
    f64::from_bits(0x3fb338ca9f24f53d), // 10
    f64::from_bits(0x3feca4b31f026aa0),
    f64::from_bits(0x3fc476a9543891ba), // 11
    f64::from_bits(0x3feb2036576afce6),
    f64::from_bits(0x3fce840b4ac4e4d2), // 12
    f64::from_bits(0x3fe9c2d163a1aa2d),
    f64::from_bits(0x3fd40645f0c6651c), // 13
    f64::from_bits(0x3fe886e6037841ed),
    f64::from_bits(0x3fd88e9c2c1b9ff8), // 14
    f64::from_bits(0x3fe767dcf5534862),
    f64::from_bits(0x3fdce0a44eb17bcc), // 15
];
