//! Coefficients for the single-precision [`crate::policy::Fast`] kernels.
//!
//! GENERATED by `tools/gen_poly.py` — do not edit by hand.
//!
//! These are this crate's own minimax approximations, not a port of anyone
//! else's: `Fast` has no upstream to be bit-exact to. Each array carries the
//! measured maximum relative error of the polynomial in isolation, which is
//! the budget the kernel then spends on argument reduction and reconstruction.
//! `tests/policy.rs` holds the finished kernels to the resulting bounds.
//!
//! Regenerate with:
//!
//! ```text
//! python3 tools/gen_poly.py
//! ```

/// `sin(r)/r` as a polynomial in `r^2`, on `|r| <= pi/4`.
///
/// Maximum relative error of the polynomial alone: 3.238e-09
pub const SIN: [f32; 4] = [
    f32::from_bits(0x3f800000), // +9.99999996761815613e-01
    f32::from_bits(0xbe2aaaa0), // -1.66666502242364539e-01
    f32::from_bits(0x3c088303), // +8.33201645289495703e-03
    f32::from_bits(0xb94c7dce), // -1.95018219953115653e-04
];

/// `cos(r)` as a polynomial in `r^2`, on `|r| <= pi/4`.
///
/// Maximum relative error of the polynomial alone: 5.607e-11
pub const COS: [f32; 5] = [
    f32::from_bits(0x3f800000), // +9.99999999943940843e-01
    f32::from_bits(0xbf000000), // -4.99999995715392831e-01
    f32::from_bits(0x3d2aaa9c), // +4.16666132319183230e-02
    f32::from_bits(0xbab60376), // -1.38865291083324323e-03
    f32::from_bits(0x37cc73ec), // +2.43726761817173652e-05
];

/// `asin(x)/x` as a polynomial in `x^2`, on `|x| <= 1/2`.
///
/// Maximum relative error of the polynomial alone: 1.512e-11
pub const ASIN: [f32; 8] = [
    f32::from_bits(0x3f800000), // +9.99999999984907073e-01
    f32::from_bits(0x3e2aaaab), // +1.66666674220321970e-01
    f32::from_bits(0x3d999947), // +7.49993817697008347e-02
    f32::from_bits(0x3d36ef8b), // +4.46620403593723375e-02
    f32::from_bits(0x3cf683d5), // +3.00921586828331901e-02
    f32::from_bits(0x3cca7071), // +2.47118192437761376e-02
    f32::from_bits(0x3becaf81), // +7.22307031951186819e-03
    f32::from_bits(0x3d0f2a39), // +3.49523778947582048e-02
];

/// `atan(x)/x` as a polynomial in `x^2`, on `|x| <= tan(pi/12)`.
///
/// Maximum relative error of the polynomial alone: 6.328e-14
pub const ATAN: [f32; 7] = [
    f32::from_bits(0x3f800000), // +9.99999999999936717e-01
    f32::from_bits(0xbeaaaaab), // -3.33333333246481622e-01
    f32::from_bits(0x3e4ccccb), // +1.99999980506415875e-01
    f32::from_bits(0xbe1248b6), // -1.42855498223958266e-01
    f32::from_bits(0x3de36b6e), // +1.11044746207634104e-01
    f32::from_bits(0xbdb75750), // -8.95220036186630680e-02
    f32::from_bits(0x3d7edc0f), // +6.22215828579366984e-02
];

/// `(exp(r) - 1)/r` as a polynomial in `r`, on `|r| <= ln(2)/2`.
///
/// Maximum relative error of the polynomial alone: 2.323e-10
pub const EXPM1: [f32; 7] = [
    f32::from_bits(0x3f800000), // +1.00000000003122369e+00
    f32::from_bits(0x3f000000), // +5.00000004664365338e-01
    f32::from_bits(0x3e2aaaaa), // +1.66666662493043544e-01
    f32::from_bits(0x3d2aaa57), // +4.16663544811033057e-02
    f32::from_bits(0x3c0888d3), // +8.33340295419591863e-03
    f32::from_bits(0x3ab6ba3e), // +1.39410030928819521e-03
    f32::from_bits(0x39500ce3), // +1.98412263858559293e-04
];

/// `atanh(s)/s` as a polynomial in `s^2`, on `|s| <= (sqrt2-1)/(sqrt2+1)`.
///
/// Maximum relative error of the polynomial alone: 7.473e-10
pub const ATANH: [f32; 4] = [
    f32::from_bits(0x3f800000), // +9.99999999253173955e-01
    f32::from_bits(0x3eaaaac5), // +3.33334126312691881e-01
    f32::from_bits(0x3e4caa65), // +1.99868757030028432e-01
    f32::from_bits(0x3e195cf0), // +1.49768596366803036e-01
];

/// `lgamma(1 + t) / (t(t - 1))` on `t` in `[0, 1]`.
/// The two zeros are factored out, so the kernel reproduces them exactly.
///
/// Maximum relative error of the polynomial alone: 5.948e-10
pub const LGAMMA: [f32; 11] = [
    f32::from_bits(0x3f13c468), // +5.77215664559069808e-01
    f32::from_bits(0xbe7b2327), // -2.45251282384232605e-01
    f32::from_bits(0x3e1f2937), // +1.55430660095279172e-01
    f32::from_bits(0xbdebb2bb), // -1.15086995695671296e-01
    f32::from_bits(0x3dbbdaf8), // +9.17262461500536058e-02
    f32::from_bits(0xbd98f08c), // -7.46775589694333441e-02
    f32::from_bits(0x3d6d3b97), // +5.79181584426461671e-02
    f32::from_bits(0xbd1e41e7), // -3.86370681143386324e-02
    f32::from_bits(0x3c9fd662), // +1.95114058737413595e-02
    f32::from_bits(0xbbcf3fc8), // -6.32474221291508786e-03
    f32::from_bits(0x3a7b9e48), // +9.59847605106592654e-04
];

/// `Gamma(1 + t)` on `t` in `[0, 1]`.
///
/// Maximum relative error of the polynomial alone: 5.876e-09
pub const GAMMA: [f32; 11] = [
    f32::from_bits(0x3f800000), // +9.99999994147594884e-01
    f32::from_bits(0xbf13c44f), // -5.77214169018388290e-01
    f32::from_bits(0x3f7d2e9a), // +9.88992305797624538e-01
    f32::from_bits(0xbf680a5e), // -9.06408180413056042e-01
    f32::from_bits(0x3f78ea85), // +9.72328475825190108e-01
    f32::from_bits(0xbf6ebcbe), // -9.32567482482609122e-01
    f32::from_bits(0x3f52fcdf), // +8.24171001464912401e-01
    f32::from_bits(0xbf192c40), // -5.98331450910515761e-01
    f32::from_bits(0x3ea3db4e), // +3.20032537720602528e-01
    f32::from_bits(0xbddcd498), // -1.07827368883278402e-01
    f32::from_bits(0x3c89d334), // +1.68243426043282740e-02
];

/// `pi/2`, split so that `n * PIO2[i]` is exact for `|n| < 2^12`.
///
/// Each part carries only its leading significand bits, with the low
/// 12 cleared; together they give `pi/2` to about 36 bits, which
/// is what keeps the reduced argument accurate when the quadrant count
/// is large.
pub const PIO2: [f32; 3] = [
    f32::from_bits(0x3fc90000), // +1.57031250000000000e+00
    f32::from_bits(0x39fda000), // +4.83751296997070312e-04
    f32::from_bits(0x33a22000), // +7.54953362047672272e-08
];

/// `2/pi`, for choosing the quadrant.
pub const TWO_OVER_PI: f32 = f32::from_bits(0x3f22f983);

/// Largest `|x|` the Cody-Waite reduction above stays exact for.
///
/// Beyond it the quadrant count exceeds what the split can multiply
/// exactly, so the kernels hand those lanes to the scalar reference
/// under `FullRange` -- and are simply wrong under `Finite`.
pub const TRIG_LIMIT: f32 = f32::from_bits(0x45c90fdb);

/// `ln(2)`, split so that `k * LN2[i]` is exact for any `k` a reduction
/// to `|r| <= ln(2)/2` can produce.
pub const LN2: [f32; 2] = [
    f32::from_bits(0x3f317000), // +6.93115234375000000e-01
    f32::from_bits(0x3805f000), // +3.19331884384155273e-05
];

/// `log2(e)`, for the exponent reduction.
pub const LOG2E: f32 = f32::from_bits(0x3fb8aa3b);

/// Stirling series coefficients for `lgamma`: `B(2n) / (2n(2n-1))`.
///
/// `lgamma(y) ~ (y - 1/2) ln y - y + ln(2 pi)/2 + sum_n S[n] / y^(2n-1)`,
/// for `y` past [`LGAMMA_CUTOFF`]. Exact rationals, computed rather than
/// fitted; the series is asymptotic, so the term count and the cutoff
/// are chosen together.
pub const STIRLING: [f32; 4] = [
    f32::from_bits(0x3daaaaab), // +8.33333333333333287e-02
    f32::from_bits(0xbb360b61), // -2.77777777777777788e-03
    f32::from_bits(0x3a500d01), // +7.93650793650793650e-04
    f32::from_bits(0xba1c09c1), // -5.95238095238095292e-04
];

/// Where the Stirling series above is truncated accurately enough.
///
/// Below this, `lgamma` walks up to it with the recurrence
/// `lgamma(y) = lgamma(y + 1) - ln(y)` and subtracts the logarithms of
/// the terms it stepped over.
pub const LGAMMA_CUTOFF: f32 = f32::from_bits(0x41000000);

/// `ln(2 pi) / 2`, the constant term of Stirling's series.
pub const HALF_LN_2PI: f32 = f32::from_bits(0x3f6b3f8e);
