//! `atan2` data: the constants `__ieee754_atan2` needs beyond
//! what `atan` (`atan_data.rs`) already provides -- the shared `d3..d13`
//! Taylor coefficients, `HPI`/`HPI1`/`MHPI` and the `1/16` band edge are
//! bit-identical between the two tables and are not repeated here.
//!
//! GENERATED by `tools/gen_tables.py` — do not edit by hand.
//!
//! Transcribed from glibc's own `sysdeps/ieee754/dbl-64/atnat2.h` (the IBM
//! Accurate Mathematical Library port -- a different upstream from
//! `exp`/`log`/`pow`'s ARM-optimized-routines, and read directly since it is
//! itself the readable C source, not a binary to reverse: glibc's trig
//! implementation predates the ARM project and was never migrated to it).
//! Copyright (C) 2001-2026 Free Software Foundation, Inc.,
//! SPDX-License-Identifier: `LGPL-2.1-or-later`. FMA placement is *not*
//! visible here -- see `src/kernels/double/trig.rs` for the disassembly this
//! was cross-checked against.
//!
//! Values are exact bit patterns; the trailing comment is the upstream
//! hex-float spelling where upstream spells one, otherwise the decimal value.


/// `pi`.
pub const OPI: f64 = f64::from_bits(0x400921fb54442d18);

/// `pi - OPI`, the low part of `pi`.
pub const OPI1: f64 = f64::from_bits(0x3ca1a62633145c07);

/// `-pi`.
pub const MOPI: f64 = f64::from_bits(0xc00921fb54442d18);

/// `pi/4`, returned for `atan2(+-inf, +-inf)`.
pub const QPI: f64 = f64::from_bits(0x3fe921fb54442d18);

/// `-pi/4`.
pub const MQPI: f64 = f64::from_bits(0xbfe921fb54442d18);

/// `3*pi/4`.
pub const TQPI: f64 = f64::from_bits(0x4002d97c7f3321d2);

/// `-3*pi/4`.
pub const MTQPI: f64 = f64::from_bits(0xc002d97c7f3321d2);

/// `2^500`, the far-apart-exponents rescale for `x`/`y`.
pub const TWO500: f64 = f64::from_bits(0x5f30000000000000);

/// `2^-500`.
pub const TWOM500: f64 = f64::from_bits(0x20b0000000000000);

