//! `j0` / `j1` / `y0` / `y1` data.
//!
//! GENERATED by `tools/gen_special_tables.py` — do not edit by hand.
//!
//! Transcribed from glibc `sysdeps/ieee754/dbl-64/e_j0.c and e_j1.c`, which is Sun Microsystems' fdlibm —
//! Copyright (c) 1993 Sun Microsystems, Inc., permission to use granted
//! provided this notice is preserved. glibc still runs this code for the
//! Bessel family, so reproducing its schedule is what makes
//! [`crate::policy::BitExact`] bit-exact here.
//!
//! Values are exact bit patterns; fdlibm's own decimal spellings carry enough
//! digits to round-trip, and the generator converts them rather than trusting
//! Rust's parser to agree.

/// `1/sqrt(pi)`.
pub const INVSQRTPI: f64 = f64::from_bits(0x3fe20dd750429b6d);

/// `2/pi`.
pub const TPI: f64 = f64::from_bits(0x3fe45f306dc9c883);

/// `j0`'s numerator on `[0, 2]`, with two leading zeros so the
/// indices match fdlibm's `R02..R05`.
pub static J0_R: [f64; 6] = [
    f64::from_bits(0x0000000000000000),
    f64::from_bits(0x0000000000000000),
    f64::from_bits(0x3f8ffffffffffffd),
    f64::from_bits(0xbf28e6a5b61ac6e9),
    f64::from_bits(0x3ebeb1d10c503919),
    f64::from_bits(0xbe33d5e773d63fce),
];

/// `j0`'s denominator on `[0, 2]`, leading zero as above.
pub static J0_S: [f64; 5] = [
    f64::from_bits(0x0000000000000000),
    f64::from_bits(0x3f8ffce882c8c2a4),
    f64::from_bits(0x3f1ea6d2dd57dbf4),
    f64::from_bits(0x3ea13b54ce84d5a9),
    f64::from_bits(0x3e1408bcf4745d8f),
];

/// `y0`'s numerator on `[0, 2]`.
pub static Y0_U: [f64; 7] = [
    f64::from_bits(0xbfb2e4d699cbd01f),
    f64::from_bits(0x3fc69d019de9e3fc),
    f64::from_bits(0xbf8c4ce8b16cfa97),
    f64::from_bits(0x3f36c54d20b29b6b),
    f64::from_bits(0xbecffea773d25cad),
    f64::from_bits(0x3e5500573b4eabd4),
    f64::from_bits(0xbdc5e43d693fb3c8),
];

/// `y0`'s denominator on `[0, 2]`.
pub static Y0_V: [f64; 4] = [
    f64::from_bits(0x3f8a127091c9c71a),
    f64::from_bits(0x3f13ecbbf578c6c1),
    f64::from_bits(0x3e91642d7ff202fd),
    f64::from_bits(0x3dfe50183bd6d9ef),
];

/// `pzero`'s numerator, one row per interval of `1/x`:
/// `[inf,8]`, `[8,4.5454]`, `[4.547,2.8571]`, `[2.8570,2]`.
pub static P0R: [[f64; 6]; 4] = [
    [
        f64::from_bits(0x0000000000000000),
        f64::from_bits(0xbfb1fffffffffd32),
        f64::from_bits(0xc02029d0b44fa779),
        f64::from_bits(0xc07011027b19e863),
        f64::from_bits(0xc0a36a6ecd4dcafc),
        f64::from_bits(0xc0b4850b36cc643d),
    ],
    [
        f64::from_bits(0xbda918b147e495cc),
        f64::from_bits(0xbfb1ffffe69afbc6),
        f64::from_bits(0xc010a370f90c6bbf),
        f64::from_bits(0xc050eb2f5a7d1783),
        f64::from_bits(0xc074b3b36742cc63),
        f64::from_bits(0xc075a6ef28a38bd7),
    ],
    [
        f64::from_bits(0xbe25e1036fe1aa86),
        f64::from_bits(0xbfb1fff6f7c0e24b),
        f64::from_bits(0xc00345b2aea48074),
        f64::from_bits(0xc035f74a4cb94e14),
        f64::from_bits(0xc04d0a22420a1a45),
        f64::from_bits(0xc03f72aca892d80f),
    ],
    [
        f64::from_bits(0xbe77d316e927026d),
        f64::from_bits(0xbfb1ff62495e1e42),
        f64::from_bits(0xbff736398a24a843),
        f64::from_bits(0xc01e8af3edafa7f3),
        f64::from_bits(0xc02662e6c5246303),
        f64::from_bits(0xc009de81af8fe70f),
    ],
];

/// `pzero`'s denominator. See [`P0R`].
pub static P0S: [[f64; 5]; 4] = [
    [
        f64::from_bits(0x405d223307a96751),
        f64::from_bits(0x40adf37d50596938),
        f64::from_bits(0x40e3d2bb6eb6b05f),
        f64::from_bits(0x40fc810f8f9fa9bd),
        f64::from_bits(0x40e741774f2c49dc),
    ],
    [
        f64::from_bits(0x404e60810c98c5de),
        f64::from_bits(0x40906d025c7e2864),
        f64::from_bits(0x40b75af88fbe1d60),
        f64::from_bits(0x40c2ccb8fa76fa38),
        f64::from_bits(0x40a2cc1dc70be864),
    ],
    [
        f64::from_bits(0x4041ed9284077dd3),
        f64::from_bits(0x40769839464a7c0e),
        f64::from_bits(0x4092a66e6d1061d6),
        f64::from_bits(0x40919ffcb8c39b7e),
        f64::from_bits(0x4065b296fc379081),
    ],
    [
        f64::from_bits(0x40363865908b5959),
        f64::from_bits(0x4061069e0ee8878f),
        f64::from_bits(0x4070e78642ea079b),
        f64::from_bits(0x40633c033ab6faff),
        f64::from_bits(0x402d50b344391809),
    ],
];

/// `qzero`'s numerator. See [`P0R`].
pub static Q0R: [[f64; 6]; 4] = [
    [
        f64::from_bits(0x0000000000000000),
        f64::from_bits(0x3fb2bffffffffe2c),
        f64::from_bits(0x402789525bb334d6),
        f64::from_bits(0x40816d6315301825),
        f64::from_bits(0x40c14d993e18f46d),
        f64::from_bits(0x40e212d40e901566),
    ],
    [
        f64::from_bits(0x3db43d8f29cc8cd9),
        f64::from_bits(0x3fb2bfffd172b04c),
        f64::from_bits(0x401757b0b9953dd3),
        f64::from_bits(0x4060e3920a8788e9),
        f64::from_bits(0x40900cf99dc8c481),
        f64::from_bits(0x409f17e953c6e3a6),
    ],
    [
        f64::from_bits(0x3e32cd036adecb82),
        f64::from_bits(0x3fb2bfee0e8d0842),
        f64::from_bits(0x400ac0fc61149cf5),
        f64::from_bits(0x40454f98962daedd),
        f64::from_bits(0x406559dbe25efd1f),
        f64::from_bits(0x4064d77c81fa21e0),
    ],
    [
        f64::from_bits(0x3e84313b54f76bdb),
        f64::from_bits(0x3fb2bec53e883e34),
        f64::from_bits(0x3ffff897e727779c),
        f64::from_bits(0x402cfdbfaaf96fe5),
        f64::from_bits(0x403faa8e29fbdc4a),
        f64::from_bits(0x403040b171814bb4),
    ],
];

/// `qzero`'s denominator. See [`P0R`].
pub static Q0S: [[f64; 6]; 4] = [
    [
        f64::from_bits(0x406478d5365b39bc),
        f64::from_bits(0x40bfa2584e6b0563),
        f64::from_bits(0x4101665254d38c3f),
        f64::from_bits(0x412883da83a52b43),
        f64::from_bits(0x4129a66b28de0b3d),
        f64::from_bits(0xc114fd6d2c9530c5),
    ],
    [
        f64::from_bits(0x4054b1b3fb5e1543),
        f64::from_bits(0x40a03ba0da21c0ce),
        f64::from_bits(0x40d267d27b591e6d),
        f64::from_bits(0x40ebb5e397e02372),
        f64::from_bits(0x40e191181f7a54a0),
        f64::from_bits(0xc0b4ea57bedbc609),
    ],
    [
        f64::from_bits(0x40486122bfe343a6),
        f64::from_bits(0x40862d8386544eb3),
        f64::from_bits(0x40acf04be44dfc63),
        f64::from_bits(0x40b93c6cd7c76a28),
        f64::from_bits(0x40a3a8aad94fb1c0),
        f64::from_bits(0xc062a7eb201cf40f),
    ],
    [
        f64::from_bits(0x403e5d96f7c07aed),
        f64::from_bits(0x4070d591e4d14b40),
        f64::from_bits(0x408a664522b3bf22),
        f64::from_bits(0x408b977c9c5cc214),
        f64::from_bits(0x406a95530e001365),
        f64::from_bits(0xc0153e6af8b32931),
    ],
];

/// `j1`'s numerator on `[0, 2]`.
pub static J1_R: [f64; 4] = [
    f64::from_bits(0xbfb0000000000000),
    f64::from_bits(0x3f570d9f98472c61),
    f64::from_bits(0xbef0c5c6ba169668),
    f64::from_bits(0x3e6aaafa46ca0bd9),
];

/// `j1`'s denominator on `[0, 2]`, leading zero as for [`J0_S`].
pub static J1_S: [f64; 6] = [
    f64::from_bits(0x0000000000000000),
    f64::from_bits(0x3f939d0b12637e53),
    f64::from_bits(0x3f285f56b9cdf664),
    f64::from_bits(0x3eb3bff8333f8498),
    f64::from_bits(0x3e35ac88c97dff2c),
    f64::from_bits(0x3dab2acfcfb97ed8),
];

/// `y1`'s numerator on `[0, 2]`.
pub static Y1_U: [f64; 5] = [
    f64::from_bits(0xbfc91866143cbc8a),
    f64::from_bits(0x3fa9d3c776292cd1),
    f64::from_bits(0xbf5f55e54844f50f),
    f64::from_bits(0x3ef8ab038fa6b88e),
    f64::from_bits(0xbe78ac00569105b8),
];

/// `y1`'s denominator on `[0, 2]`.
pub static Y1_V: [f64; 5] = [
    f64::from_bits(0x3f94650d3f4da9f0),
    f64::from_bits(0x3f2a8c896c257764),
    f64::from_bits(0x3eb6c05a894e8ca6),
    f64::from_bits(0x3e3abf1d5ba69a86),
    f64::from_bits(0x3db25039daca772a),
];

/// `pone`'s numerator, one row per interval of `1/x`. See [`P0R`].
pub static P1R: [[f64; 6]; 4] = [
    [
        f64::from_bits(0x0000000000000000),
        f64::from_bits(0x3fbdfffffffffcce),
        f64::from_bits(0x402a7a9d357f7fce),
        f64::from_bits(0x4079c0d4652ea590),
        f64::from_bits(0x40ae457da3a532cc),
        f64::from_bits(0x40beea7ac32782dd),
    ],
    [
        f64::from_bits(0x3dad0667dae1ca7d),
        f64::from_bits(0x3fbdffffe2c10043),
        f64::from_bits(0x401b36046e6315e3),
        f64::from_bits(0x405b13b9452602ed),
        f64::from_bits(0x40802d16d052d649),
        f64::from_bits(0x408085b8bb7e0cb7),
    ],
    [
        f64::from_bits(0x3e29fc21a7ad9edd),
        f64::from_bits(0x3fbdfff55b21d17b),
        f64::from_bits(0x400f76bce85ead8a),
        f64::from_bits(0x40418f489da6d129),
        f64::from_bits(0x4056c3854d2c1837),
        f64::from_bits(0x4048478f8ea83ee5),
    ],
    [
        f64::from_bits(0x3e7ce9d4f65544f4),
        f64::from_bits(0x3fbdff42be760d83),
        f64::from_bits(0x4002f2b7f98faec0),
        f64::from_bits(0x40287c377f71a964),
        f64::from_bits(0x4031b1a8177f8ee2),
        f64::from_bits(0x40144b49a574c1fe),
    ],
];

/// `pone`'s denominator. See [`P0R`].
pub static P1S: [[f64; 5]; 4] = [
    [
        f64::from_bits(0x405c8d458e656cac),
        f64::from_bits(0x40ac85dc964d274f),
        f64::from_bits(0x40e20b8697c5bb7f),
        f64::from_bits(0x40f7d42cb28f17bb),
        f64::from_bits(0x40de1511697a0b2d),
    ],
    [
        f64::from_bits(0x404da3eaa8af633d),
        f64::from_bits(0x408efb361b066701),
        f64::from_bits(0x40b4e9445706b6fb),
        f64::from_bits(0x40bea4b0b8a5bb15),
        f64::from_bits(0x40978030036f5e51),
    ],
    [
        f64::from_bits(0x40416549a134069c),
        f64::from_bits(0x40750c3307f1a75f),
        f64::from_bits(0x40905b7c5037d523),
        f64::from_bits(0x408bd67da32e31e9),
        f64::from_bits(0x4059f26d7c2eed53),
    ],
    [
        f64::from_bits(0x40356fbd8ad5ecdc),
        f64::from_bits(0x405f529314f92cd5),
        f64::from_bits(0x406d08d8d5a2dbd9),
        f64::from_bits(0x405d6b7ada1884a9),
        f64::from_bits(0x4020bab1f44e5192),
    ],
];

/// `qone`'s numerator. See [`P0R`].
pub static Q1R: [[f64; 6]; 4] = [
    [
        f64::from_bits(0x0000000000000000),
        f64::from_bits(0xbfba3ffffffffdf3),
        f64::from_bits(0xc0304591a26779f7),
        f64::from_bits(0xc087bcd053e4b576),
        f64::from_bits(0xc0c724e740f87415),
        f64::from_bits(0xc0e7a6d065d09c6a),
    ],
    [
        f64::from_bits(0xbdb6fa431aa1a098),
        f64::from_bits(0xbfba3fffcb597fef),
        f64::from_bits(0xc0201ce6ca03ad4b),
        f64::from_bits(0xc066f56d6ca7b9b0),
        f64::from_bits(0xc09574c66931734f),
        f64::from_bits(0xc0a468e388fda79d),
    ],
    [
        f64::from_bits(0xbe35cfa9d38fc84f),
        f64::from_bits(0xbfba3feb51aeed54),
        f64::from_bits(0xc01270c23302d9ff),
        f64::from_bits(0xc04cec71c25d16da),
        f64::from_bits(0xc06c87d34718d55f),
        f64::from_bits(0xc06b66b95f5c1bf6),
    ],
    [
        f64::from_bits(0xbe87f12644c626d2),
        f64::from_bits(0xbfba3e8e9148b010),
        f64::from_bits(0xc006048469bb4eda),
        f64::from_bits(0xc033a9e2c168907f),
        f64::from_bits(0xc04529a3de104aaa),
        f64::from_bits(0xc0355f3639cf6e52),
    ],
];

/// `qone`'s denominator. See [`P0R`].
pub static Q1S: [[f64; 6]; 4] = [
    [
        f64::from_bits(0x40642ca6de5bcde5),
        f64::from_bits(0x40be9162d0d88419),
        f64::from_bits(0x4100579ab0b75e98),
        f64::from_bits(0x4125f65372869c19),
        f64::from_bits(0x412457d27719ad5c),
        f64::from_bits(0xc111f9690ea5aa18),
    ],
    [
        f64::from_bits(0x405451b2ff5a11b2),
        f64::from_bits(0x409f1f31e77bf839),
        f64::from_bits(0x40d10f1f0d64ce29),
        f64::from_bits(0x40e8576daabad197),
        f64::from_bits(0x40db4b04cf7c364b),
        f64::from_bits(0xc0b26f2efcffa004),
    ],
    [
        f64::from_bits(0x4047d523ccd367e4),
        f64::from_bits(0x40850eebc031ee3e),
        f64::from_bits(0x40aa684e448e7c9a),
        f64::from_bits(0x40b5abbaa61d54a6),
        f64::from_bits(0x409dbc7a0dd4df4b),
        f64::from_bits(0xc060e670290a311f),
    ],
    [
        f64::from_bits(0x403d888a78ae64ff),
        f64::from_bits(0x406f9f68db821cba),
        f64::from_bits(0x4087ac05ce49a0f7),
        f64::from_bits(0x40871b2548d4c029),
        f64::from_bits(0x40637e5e3c3ed8d4),
        f64::from_bits(0xc013d686e71be86b),
    ],
];
