//! `exp10` data: the reduction constants and the degree-4 correction.
//!
//! GENERATED by `tools/gen_tables.py` — do not edit by hand.
//!
//! Transcribed from glibc's `sysdeps/ieee754/dbl-64/e_exp_data.c`, the
//! `invlog10_2N` / `neglog10_2hiN` / `neglog10_2loN` / `exp10_poly` members of
//! `__exp_data`. The 128-entry `2^(k/128)` table is *the same table* `exp` and
//! `exp2` use — glibc shares one — so it is not duplicated here; see
//! [`super::exp::TAB`].
//!
//! Values are exact bit patterns; the trailing comment is the upstream
//! hex-float spelling, `N = 128`.

/// `N * log2(10)`. Argument reduction scale: `k = round(x * INVLOG10_2N)`.
/// Upstream: `0x1.a934f0979a371p1 * N`.
pub const INVLOG10_2N: f64 = f64::from_bits(0x407a934f0979a371);

/// `-log10(2)/N`, high part. Exact in the reduction `x + kd*NEGLOG10_2HIN`.
/// Upstream: `-0x1.3441350ap-2 / N`.
pub const NEGLOG10_2HIN: f64 = f64::from_bits(0xbf63441350a00000);

/// `-log10(2)/N`, low part.
///
/// Positive, despite the name: glibc spells it `0x1.0c0219dc1da99p-39 / N`
/// and *adds* it, because the high part above overshoots.
/// Upstream: `0x1.0c0219dc1da99p-39 / N`.
pub const NEGLOG10_2LON: f64 = f64::from_bits(0x3d10c0219dc1da99);

/// `exp10` minimax coefficients for `10^(r/N) - 1`, in glibc's order:
/// `tail + r*(C0 + r*C1 + r^2*(C2 + r*C3 + r^2*C4))`.
/// Upstream: `0x1.26bb1bbb55516p1`.
pub const C0: f64 = f64::from_bits(0x40026bb1bbb55516);
/// Upstream: `0x1.53524c73ce9fep1`.
pub const C1: f64 = f64::from_bits(0x40053524c73ce9fe);
/// Upstream: `0x1.0470591ce4b26p1`.
pub const C2: f64 = f64::from_bits(0x4000470591ce4b26);
/// Upstream: `0x1.2bd76577fe684p0`.
pub const C3: f64 = f64::from_bits(0x3ff2bd76577fe684);
/// Upstream: `0x1.1446eeccd0efbp-1`.
pub const C4: f64 = f64::from_bits(0x3fe1446eeccd0efb);

/// `log10(DBL_MAX)`: at or above this, `exp10` overflows.
/// Upstream: `0x1.34413509f79ffp8`.
pub const OFLOW_BOUND: f64 = f64::from_bits(0x40734413509f79ff);

/// `-350`: below this, `exp10` underflows to zero.
pub const UFLOW_BOUND: f64 = -350.0;

/// `top12(0x1p-57)`, the low end of the reduction's useful range.
pub const SMALL_TOP: u32 = 0x3c6;

/// `BigTop - SmallTop`, the width of that range in exponent-field units.
pub const THRESH: u32 = 0x41;

/// `(ln 10)^k / k!` for `k` in `1..=13`, the Taylor coefficients of `10^r`.
///
/// For the table-free [`crate::policy::Fast`] path only. Truncating here
/// leaves a relative error of `(r ln 10)^14 / 14!`, which at the reduction's
/// worst case `|r| = log10(2)/2` is about `6.5e-18`.
pub static G: [f64; 13] = [
    f64::from_bits(0x40026bb1bbb55516),
    f64::from_bits(0x40053524c73cea69),
    f64::from_bits(0x4000470591de2ca4),
    f64::from_bits(0x3ff2bd7609fd98c4),
    f64::from_bits(0x3fe1429ffd1d4d76),
    f64::from_bits(0x3fca7ed70847c8b6),
    f64::from_bits(0x3fb16e4dfc333a87),
    f64::from_bits(0x3f94116b05fdaa5d),
    f64::from_bits(0x3f74897c45d93d42),
    f64::from_bits(0x3f52ea52b2d182af),
    f64::from_bits(0x3f2facfd5d909d64),
    f64::from_bits(0x3f084fe12df80be4),
    f64::from_bits(0x3ee1398ad2c41708),
];

/// `log2(10)`, for the table-free reduction.
pub const LOG2_10: f64 = f64::from_bits(0x400a934f0979a371);

/// `log10(2)`, split so that `kd * LOG10_2HI` is exact for every `kd` the
/// reduction produces. Rounding either piece to its shortest round-tripping
/// decimal form destroys that property.
pub const LOG10_2HI: f64 = f64::from_bits(0x3fd3441350a00000);
/// `log10(2)`, low part. See [`LOG10_2HI`].
pub const LOG10_2LO: f64 = f64::from_bits(0xbd80c0219dc1da99);
