//! Coefficients for the double-precision [`crate::policy::Fast`] kernels.
//!
//! GENERATED by `tools/gen_poly.py` — do not edit by hand.
//!
//! These are this crate's own minimax approximations, not a port of anyone
//! else's: `Fast` has no upstream to be bit-exact to. Each array carries the
//! measured maximum relative error of the polynomial in isolation, which is
//! the budget the kernel then spends on argument reduction and reconstruction.
//! `tests/policy.rs` holds the finished kernels to the resulting bounds.
//!
//! Regenerate with:
//!
//! ```text
//! python3 tools/gen_poly.py
//! ```

/// `sin(r)/r` as a polynomial in `r^2`, on `|r| <= pi/4`.
///
/// Maximum relative error of the polynomial alone: 1.881e-21
pub const SIN: [f64; 8] = [
    f64::from_bits(0x3ff0000000000000), // +1.00000000000000000e+00
    f64::from_bits(0xbfc5555555555555), // -1.66666666666666657e-01
    f64::from_bits(0x3f8111111111110a), // +8.33333333333332107e-03
    f64::from_bits(0xbf2a01a01a0187fb), // -1.98412698412531039e-04
    f64::from_bits(0x3ec71de3a53099c1), // +2.75573192133894976e-06
    f64::from_bits(0xbe5ae6452640fc60), // -2.50521047381241889e-08
    f64::from_bits(0x3de612075db6aba2), // +1.60583476079676460e-10
    f64::from_bits(0xbd6aa989383e2f3c), // -7.57786723864914201e-13
];

/// `cos(r)` as a polynomial in `r^2`, on `|r| <= pi/4`.
///
/// Maximum relative error of the polynomial alone: 3.587e-20
pub const COS: [f64; 8] = [
    f64::from_bits(0x3ff0000000000000), // +1.00000000000000000e+00
    f64::from_bits(0xbfe0000000000000), // -5.00000000000000000e-01
    f64::from_bits(0x3fa5555555555533), // +4.16666666666664284e-02
    f64::from_bits(0xbf56c16c16c1362c), // -1.38888888888589589e-03
    f64::from_bits(0x3efa01a019ad75d2), // +2.48015872828988816e-05
    f64::from_bits(0xbe927e4f6fe1c83c), // -2.75573128655858554e-07
    f64::from_bits(0x3e21ee9547751192), // +2.08755551357255980e-09
    f64::from_bits(0xbda8f6ad5295e573), // -1.13521228708983166e-11
];

/// `asin(x)/x` as a polynomial in `x^2`, on `|x| <= 1/2`.
///
/// Maximum relative error of the polynomial alone: 1.698e-23
pub const ASIN: [f64; 18] = [
    f64::from_bits(0x3ff0000000000000), // +1.00000000000000000e+00
    f64::from_bits(0x3fc5555555555555), // +1.66666666666666657e-01
    f64::from_bits(0x3fb3333333333332), // +7.49999999999999833e-02
    f64::from_bits(0x3fa6db6db6db6f76), // +4.46428571428602455e-02
    f64::from_bits(0x3f9f1c71c71b3b96), // +3.03819444441689387e-02
    f64::from_bits(0x3f96e8ba2ecd0818), // +2.23721591057782498e-02
    f64::from_bits(0x3f91c4ec45a7d7c3), // +1.73527638925958898e-02
    f64::from_bits(0x3f8c999b5f19ec79), // +1.39648569486239150e-02
    f64::from_bits(0x3f87a858a0b46b43), // +1.15515636485291669e-02
    f64::from_bits(0x3f83ff8c385e91c3), // +9.76476237321655637e-03
    f64::from_bits(0x3f811e7c6a346b5d), // +8.35892867194381640e-03
    f64::from_bits(0x3f7eeb1bd5b476e0), // +7.54843590700968181e-03
    f64::from_bits(0x3f74f1fbe2d2d5ef), // +5.11358635883628256e-03
    f64::from_bits(0x3f873fc6490b132a), // +1.13521090546640675e-02
    f64::from_bits(0xbf889cdb092363eb), // -1.20179283298273622e-02
    f64::from_bits(0x3fa518bff5c3fd1a), // +4.12044513232052295e-02
    f64::from_bits(0xbfa7364c17ba322b), // -4.53361300434134903e-02
    f64::from_bits(0x3fa3bcc1d318361b), // +3.85494775947387777e-02
];

/// `atan(x)/x` as a polynomial in `x^2`, on `|x| <= tan(pi/12)`.
///
/// Maximum relative error of the polynomial alone: 5.945e-23
pub const ATAN: [f64; 12] = [
    f64::from_bits(0x3ff0000000000000), // +1.00000000000000000e+00
    f64::from_bits(0xbfd5555555555555), // -3.33333333333333315e-01
    f64::from_bits(0x3fc9999999999994), // +1.99999999999999845e-01
    f64::from_bits(0xbfc2492492491eb6), // -1.42857142857101216e-01
    f64::from_bits(0x3fbc71c71c6b986c), // +1.11111111105488269e-01
    f64::from_bits(0xbfb745d1726ffa0c), // -9.09090904606061900e-02
    f64::from_bits(0x3fb3b13ab2220656), // +7.69230542082593727e-02
    f64::from_bits(0xbfb1110453e3e4fd), // -6.66659073648538519e-02
    f64::from_bits(0x3fae1be38affcbde), // +5.88065249611628843e-02
    f64::from_bits(0xbfaad14e88fbeba3), // -5.23781339852214187e-02
    f64::from_bits(0x3fa722b5e5a5c462), // +4.51866953689055301e-02
    f64::from_bits(0xbf9e43cd6e0d1578), // -2.95555208606592401e-02
];

/// `(exp(r) - 1)/r` as a polynomial in `r`, on `|r| <= ln(2)/2`.
///
/// Maximum relative error of the polynomial alone: 1.764e-17
pub const EXPM1: [f64; 11] = [
    f64::from_bits(0x3ff0000000000000), // +1.00000000000000000e+00
    f64::from_bits(0x3fe0000000000005), // +5.00000000000000555e-01
    f64::from_bits(0x3fc5555555555530), // +1.66666666666665630e-01
    f64::from_bits(0x3fa555555555211f), // +4.16666666665739191e-02
    f64::from_bits(0x3f8111111111a225), // +8.33333333339776085e-03
    f64::from_bits(0x3f56c16c17f29760), // +1.38888889322560244e-03
    f64::from_bits(0x3f2a01a0171171af), // +1.98412697076555980e-04
    f64::from_bits(0x3efa019a6b339901), // +2.48015046055089331e-05
    f64::from_bits(0x3ec71de8e393f38e), // +2.75574145958000187e-06
    f64::from_bits(0x3e928a27d488a9bd), // +2.76262615036628745e-07
    f64::from_bits(0x3e5ae6496547b0ca), // +2.50521650801994365e-08
];

/// `atanh(s)/s` as a polynomial in `s^2`, on `|s| <= (sqrt2-1)/(sqrt2+1)`.
///
/// Maximum relative error of the polynomial alone: 9.094e-21
pub const ATANH: [f64; 9] = [
    f64::from_bits(0x3ff0000000000000), // +1.00000000000000000e+00
    f64::from_bits(0x3fd5555555555554), // +3.33333333333333259e-01
    f64::from_bits(0x3fc9999999999fb5), // +2.00000000000043393e-01
    f64::from_bits(0x3fc24924924102d5), // +1.42857142842351209e-01
    f64::from_bits(0x3fbc71c727494bf4), // +1.11111113635430858e-01
    f64::from_bits(0x3fb745cd6666f261), // +9.09088492398466702e-02
    f64::from_bits(0x3fb3b21e8dfd4ed1), // +7.69366356519711886e-02
    f64::from_bits(0x3fb0f4261db4cdb9), // +6.62254164242800508e-02
    f64::from_bits(0x3fb10486a28a5703), // +6.64753100230335708e-02
];

/// `(atanh(s)/s - 1 - s^2/3) / s^4` as a polynomial in `s^2`, on the
/// interval of [`ATANH`]: the series without its first two terms, for
/// a caller that carries both of them in double-double.
///
/// Maximum relative error of the polynomial alone: 7.805e-16
pub const ATANH_TAIL: [f64; 7] = [
    f64::from_bits(0x3fc999999999999f), // +2.00000000000000150e-01
    f64::from_bits(0x3fc249249248dcf4), // +1.42857142856633978e-01
    f64::from_bits(0x3fbc71c71d9b56ad), // +1.11111111381741082e-01
    f64::from_bits(0x3fb745d08cdb4236), // +9.09090370071304610e-02
    f64::from_bits(0x3fb3b190ab7f7b45), // +7.69281786628939895e-02
    f64::from_bits(0x3fb100e2e259e907), // +6.64197733512176119e-02
    f64::from_bits(0x3fb08f8e8ce61159), // +6.46905035010311297e-02
];

/// `lgamma(1 + t) / (t(t - 1))` on `t` in `[0, 1]`.
/// The two zeros are factored out, so the kernel reproduces them exactly.
///
/// Maximum relative error of the polynomial alone: 5.516e-21
pub const LGAMMA: [f64; 25] = [
    f64::from_bits(0x3fe2788cfc6fb619), // +5.77215664901532866e-01
    f64::from_bits(0xbfcf6465978d46e9), // -2.45251368522580365e-01
    f64::from_bits(0x3fc3e54520481ea6), // +1.55434265863950205e-01
    f64::from_bits(0xbfbd7a3e6a8f0f38), // -1.15146542563761112e-01
    f64::from_bits(0x3fb79cf9c4c20a25), // +9.22390084615832412e-02
    f64::from_bits(0xbfb3cb1f9cd87ffb), // -7.73181684421614807e-02
    f64::from_bits(0x3fb11554971ea2c9), // +6.67317265457639947e-02
    f64::from_bits(0xbfae1823ad1bea15), // -5.87779187025782371e-02
    f64::from_bits(0x3faae8a2140e89d3), // +5.25560998423945311e-02
    f64::from_bits(0xbfa85759339b009f), // -4.75414157385796107e-02
    f64::from_bits(0x3fa638998c0945a8), // +4.34005721514368337e-02
    f64::from_bits(0xbfa46ce85dc6e1ea), // -3.98933996652351547e-02
    f64::from_bits(0x3fa2d6f42d100381), // +3.67962174423217617e-02
    f64::from_bits(0xbfa15159b0461fdb), // -3.38237788847092977e-02
    f64::from_bits(0x3f9f4fd14021f85b), // +3.05779166596881029e-02
    f64::from_bits(0xbf9b3f48b5c664a3), // -2.66085968920363285e-02
    f64::from_bits(0x3f962be3295f2147), // +2.16517919541570313e-02
    f64::from_bits(0xbf9050f344a6cd34), // -1.59338007594673342e-02
    f64::from_bits(0x3f84f83b84e6ee55), // +1.02390909131521522e-02
    f64::from_bits(0xbf76b25b248edc2b), // -5.54118731172707334e-03
    f64::from_bits(0x3f63e2f69f1b17b8), // +2.42756050360789719e-03
    f64::from_bits(0xbf4adfbee5d0394a), // -8.20129596492505082e-04
    f64::from_bits(0x3f2a2084805d6a17), // +1.99333357324985651e-04
    f64::from_bits(0xbf0032576c0c8494), // -3.08926514718334581e-05
    f64::from_bits(0x3ec32da58746d56c), // +2.28623235384399990e-06
];

/// `Gamma(1 + t)` on `t` in `[0, 1]`.
///
/// Maximum relative error of the polynomial alone: 1.126e-19
pub const GAMMA: [f64; 25] = [
    f64::from_bits(0x3ff0000000000000), // +1.00000000000000000e+00
    f64::from_bits(0xbfe2788cfc6fb618), // -5.77215664901532755e-01
    f64::from_bits(0x3fefa658c23b1464), // +9.89055995327941861e-01
    f64::from_bits(0xbfed0a118f31efa0), // -9.07479076078278268e-01
    f64::from_bits(0x3fef6a5105405aa0), // +9.81728086716277204e-01
    f64::from_bits(0xbfef6c80ea733406), // -9.81995065603428641e-01
    f64::from_bits(0x3fefc7e08592ff0d), // +9.93149052512281139e-01
    f64::from_bits(0xbfefdf3d54fc8026), // -9.96000925053526442e-01
    f64::from_bits(0x3feff069cca0fbcb), // +9.98097324052531376e-01
    f64::from_bits(0xbfeff77cc5874d64), // -9.98960862920665438e-01
    f64::from_bits(0x3feff8d734d93ba5), // +9.99126055927139434e-01
    f64::from_bits(0xbfefee8cdb4bf561), // -9.97869900049107028e-01
    f64::from_bits(0x3fefc235a4b0f73d), // +9.92457219755784714e-01
    f64::from_bits(0xbfef3af2d3e46844), // -9.75945867397293387e-01
    f64::from_bits(0x3fedf004f1317a0b), // +9.35549231606104370e-01
    f64::from_bits(0xbfeb5c00dec43444), // -8.54980883684796300e-01
    f64::from_bits(0x3fe7288ae29d9cf1), // +7.23699038132421646e-01
    f64::from_bits(0xbfe194026d8b373c), // -5.49317563965565636e-01
    f64::from_bits(0x3fd7242e2d42ae3f), // +3.61583275031737317e-01
    f64::from_bits(0xbfc985a63db87a54), // -1.99391155373592199e-01
    f64::from_bits(0x3fb6b2a542f8786c), // +8.86634148123179311e-02
    f64::from_bits(0xbf9f0bbb089ef1b3), // -3.03181861888661246e-02
    f64::from_bits(0x3f7e7cac22eb25d8), // +7.44311562329743465e-03
    f64::from_bits(0xbf530fa0651ccbe3), // -1.16339362689354335e-03
    f64::from_bits(0x3f16bcb5e498640f), // +8.67353457113669658e-05
];

/// `pi/2`, split so that `n * PIO2[i]` is exact for `|n| < 2^20`.
///
/// Each part carries only its leading significand bits, with the low
/// 20 cleared; together they give `pi/2` to about 99 bits, which
/// is what keeps the reduced argument accurate when the quadrant count
/// is large.
pub const PIO2: [f64; 3] = [
    f64::from_bits(0x3ff921fb54400000), // +1.57079632673412561e+00
    f64::from_bits(0x3dd0b4611a600000), // +6.07710050630396598e-11
    f64::from_bits(0x3ba3198a2e000000), // +2.02226624871116646e-21
];

/// `2/pi`, for choosing the quadrant.
pub const TWO_OVER_PI: f64 = f64::from_bits(0x3fe45f306dc9c883);

/// Largest `|x|` the Cody-Waite reduction above stays exact for.
///
/// Beyond it the quadrant count exceeds what the split can multiply
/// exactly, so the kernels hand those lanes to the scalar reference
/// under `FullRange` -- and are simply wrong under `Finite`.
pub const TRIG_LIMIT: f64 = f64::from_bits(0x413921fb54442d18);

/// `ln(2)`, split so that `k * LN2[i]` is exact for any `k` a reduction
/// to `|r| <= ln(2)/2` can produce.
pub const LN2: [f64; 2] = [
    f64::from_bits(0x3fe62e42fef00000), // +6.93147180485539138e-01
    f64::from_bits(0x3dd473de6af00000), // +7.44061710980297927e-11
];

/// `log2(e)`, for the exponent reduction.
pub const LOG2E: f64 = f64::from_bits(0x3ff71547652b82fe);

/// The residue of [`LOG2E`]: `log2(e) - LOG2E`, rounded once, so that
/// `LOG2E + LOG2E_LO` is `log2(e)` to roughly twice the working
/// precision.
pub const LOG2E_LO: f64 = f64::from_bits(0x3c7777d0ffda0d24);

/// `log2(e)/3` and its residue, the scale of the `s^3` term of the
/// base-2 logarithm's `atanh` series, split like [`LOG2E`] /
/// [`LOG2E_LO`] and for the same caller.
pub const THIRD_LOG2E: f64 = f64::from_bits(0x3fdec709dc3a03fd);

/// See [`THIRD_LOG2E`].
pub const THIRD_LOG2E_LO: f64 = f64::from_bits(0x3c7d27f05548af0c);

/// Stirling series coefficients for `lgamma`: `B(2n) / (2n(2n-1))`.
///
/// `lgamma(y) ~ (y - 1/2) ln y - y + ln(2 pi)/2 + sum_n S[n] / y^(2n-1)`,
/// for `y` past [`LGAMMA_CUTOFF`]. Exact rationals, computed rather than
/// fitted; the series is asymptotic, so the term count and the cutoff
/// are chosen together.
pub const STIRLING: [f64; 7] = [
    f64::from_bits(0x3fb5555555555555), // +8.33333333333333287e-02
    f64::from_bits(0xbf66c16c16c16c17), // -2.77777777777777788e-03
    f64::from_bits(0x3f4a01a01a01a01a), // +7.93650793650793650e-04
    f64::from_bits(0xbf43813813813814), // -5.95238095238095292e-04
    f64::from_bits(0x3f4b951e2b18ff23), // +8.41750841750841714e-04
    f64::from_bits(0xbf5f6ab0d9993c7d), // -1.91752691752691763e-03
    f64::from_bits(0x3f7a41a41a41a41a), // +6.41025641025641003e-03
];

/// Where the Stirling series above is truncated accurately enough.
///
/// Below this, `lgamma` walks up to it with the recurrence
/// `lgamma(y) = lgamma(y + 1) - ln(y)` and subtracts the logarithms of
/// the terms it stepped over.
pub const LGAMMA_CUTOFF: f64 = f64::from_bits(0x4020000000000000);

/// `ln(2 pi) / 2`, the constant term of Stirling's series.
pub const HALF_LN_2PI: f64 = f64::from_bits(0x3fed67f1c864beb5);
