//! `pow` data: the 128-subinterval log table, carried in double-double.
//!
//! GENERATED by `tools/gen_tables.py` — do not edit by hand.
//!
//! Transcribed from ARM optimized-routines `math/pow_log_data.c` (N = 128),
//! Copyright (c) 2018-2023 Arm Limited, SPDX-License-Identifier:
//! `MIT OR Apache-2.0 WITH LLVM-exception`. Byte-identical to the table glibc
//! compiles into `__ieee754_pow_fma`, which is what lets
//! [`crate::policy::BitExact`] mean *bit*-exact and not merely accurate.
//!
//! Values are exact bit patterns; the trailing comment is the upstream
//! hex-float spelling.

/// ln(2), high part.
/// Upstream: `0x1.62e42fefa3800p-1`.
pub const LN2HI: f64 = f64::from_bits(0x3fe62e42fefa3800);

/// ln(2), low part.
/// Upstream: `0x1.ef35793c76730p-45`.
pub const LN2LO: f64 = f64::from_bits(0x3d2ef35793c76730);

/// Coefficients for `log(1 + r) - r`; the first-order term is 1 and is
/// not stored.
/// Upstream: `-0x1.0000000000000p-1`.
pub const A0: f64 = f64::from_bits(0xbfe0000000000000);
/// Upstream: `-0x1.5555555555560p-1`.
pub const A1: f64 = f64::from_bits(0xbfe5555555555560);
/// Upstream: `0x1.0000000000006p-1`.
pub const A2: f64 = f64::from_bits(0x3fe0000000000006);
/// Upstream: `0x1.999999959554ep-1`.
pub const A3: f64 = f64::from_bits(0x3fe999999959554e);
/// Upstream: `-0x1.555555529a47ap-1`.
pub const A4: f64 = f64::from_bits(0xbfe555555529a47a);
/// Upstream: `-0x1.2495b9b4845e9p+0`.
pub const A5: f64 = f64::from_bits(0xbff2495b9b4845e9);
/// Upstream: `0x1.0002b8b263fc3p+0`.
pub const A6: f64 = f64::from_bits(0x3ff0002b8b263fc3);

/// `[invc, logc, logctail]` interleaved for each of the 128
/// subintervals. `pow` needs the logarithm to more than double
/// precision, so `log(c)` is carried as an unevaluated sum of two
/// doubles rather than one.
///
/// Upstream stores a fourth, unused padding field per entry to make the
/// C index arithmetic a shift; there is no such benefit here, so it is
/// dropped and the stride is 3.
pub static TAB: [f64; 384] = [
    f64::from_bits(0x3ff6a00000000000),
    f64::from_bits(0xbfd62c82f2b9c800),
    f64::from_bits(0x3cfab42428375680), // 0
    f64::from_bits(0x3ff6800000000000),
    f64::from_bits(0xbfd5d1bdbf580800),
    f64::from_bits(0xbd1ca508d8e0f720), // 1
    f64::from_bits(0x3ff6600000000000),
    f64::from_bits(0xbfd5767717455800),
    f64::from_bits(0xbd2362a4d5b6506d), // 2
    f64::from_bits(0x3ff6400000000000),
    f64::from_bits(0xbfd51aad872df800),
    f64::from_bits(0xbce684e49eb067d5), // 3
    f64::from_bits(0x3ff6200000000000),
    f64::from_bits(0xbfd4be5f95777800),
    f64::from_bits(0xbd041b6993293ee0), // 4
    f64::from_bits(0x3ff6000000000000),
    f64::from_bits(0xbfd4618bc21c6000),
    f64::from_bits(0x3d13d82f484c84cc), // 5
    f64::from_bits(0x3ff5e00000000000),
    f64::from_bits(0xbfd404308686a800),
    f64::from_bits(0x3cdc42f3ed820b3a), // 6
    f64::from_bits(0x3ff5c00000000000),
    f64::from_bits(0xbfd3a64c55694800),
    f64::from_bits(0x3d20b1c686519460), // 7
    f64::from_bits(0x3ff5a00000000000),
    f64::from_bits(0xbfd347dd9a988000),
    f64::from_bits(0x3d25594dd4c58092), // 8
    f64::from_bits(0x3ff5800000000000),
    f64::from_bits(0xbfd2e8e2bae12000),
    f64::from_bits(0x3d267b1e99b72bd8), // 9
    f64::from_bits(0x3ff5600000000000),
    f64::from_bits(0xbfd2895a13de8800),
    f64::from_bits(0x3d15ca14b6cfb03f), // 10
    f64::from_bits(0x3ff5600000000000),
    f64::from_bits(0xbfd2895a13de8800),
    f64::from_bits(0x3d15ca14b6cfb03f), // 11
    f64::from_bits(0x3ff5400000000000),
    f64::from_bits(0xbfd22941fbcf7800),
    f64::from_bits(0xbd165a242853da76), // 12
    f64::from_bits(0x3ff5200000000000),
    f64::from_bits(0xbfd1c898c1699800),
    f64::from_bits(0xbd1fafbc68e75404), // 13
    f64::from_bits(0x3ff5000000000000),
    f64::from_bits(0xbfd1675cababa800),
    f64::from_bits(0x3d1f1fc63382a8f0), // 14
    f64::from_bits(0x3ff4e00000000000),
    f64::from_bits(0xbfd1058bf9ae4800),
    f64::from_bits(0xbd26a8c4fd055a66), // 15
    f64::from_bits(0x3ff4c00000000000),
    f64::from_bits(0xbfd0a324e2739000),
    f64::from_bits(0xbd0c6bee7ef4030e), // 16
    f64::from_bits(0x3ff4a00000000000),
    f64::from_bits(0xbfd0402594b4d000),
    f64::from_bits(0xbcf036b89ef42d7f), // 17
    f64::from_bits(0x3ff4a00000000000),
    f64::from_bits(0xbfd0402594b4d000),
    f64::from_bits(0xbcf036b89ef42d7f), // 18
    f64::from_bits(0x3ff4800000000000),
    f64::from_bits(0xbfcfb9186d5e4000),
    f64::from_bits(0x3d0d572aab993c87), // 19
    f64::from_bits(0x3ff4600000000000),
    f64::from_bits(0xbfcef0adcbdc6000),
    f64::from_bits(0x3d2b26b79c86af24), // 20
    f64::from_bits(0x3ff4400000000000),
    f64::from_bits(0xbfce27076e2af000),
    f64::from_bits(0xbd172f4f543fff10), // 21
    f64::from_bits(0x3ff4200000000000),
    f64::from_bits(0xbfcd5c216b4fc000),
    f64::from_bits(0x3d21ba91bbca681b), // 22
    f64::from_bits(0x3ff4000000000000),
    f64::from_bits(0xbfcc8ff7c79aa000),
    f64::from_bits(0x3d27794f689f8434), // 23
    f64::from_bits(0x3ff4000000000000),
    f64::from_bits(0xbfcc8ff7c79aa000),
    f64::from_bits(0x3d27794f689f8434), // 24
    f64::from_bits(0x3ff3e00000000000),
    f64::from_bits(0xbfcbc286742d9000),
    f64::from_bits(0x3d194eb0318bb78f), // 25
    f64::from_bits(0x3ff3c00000000000),
    f64::from_bits(0xbfcaf3c94e80c000),
    f64::from_bits(0x3cba4e633fcd9066), // 26
    f64::from_bits(0x3ff3a00000000000),
    f64::from_bits(0xbfca23bc1fe2b000),
    f64::from_bits(0xbd258c64dc46c1ea), // 27
    f64::from_bits(0x3ff3a00000000000),
    f64::from_bits(0xbfca23bc1fe2b000),
    f64::from_bits(0xbd258c64dc46c1ea), // 28
    f64::from_bits(0x3ff3800000000000),
    f64::from_bits(0xbfc9525a9cf45000),
    f64::from_bits(0xbd2ad1d904c1d4e3), // 29
    f64::from_bits(0x3ff3600000000000),
    f64::from_bits(0xbfc87fa06520d000),
    f64::from_bits(0x3d2bbdbf7fdbfa09), // 30
    f64::from_bits(0x3ff3400000000000),
    f64::from_bits(0xbfc7ab890210e000),
    f64::from_bits(0x3d2bdb9072534a58), // 31
    f64::from_bits(0x3ff3400000000000),
    f64::from_bits(0xbfc7ab890210e000),
    f64::from_bits(0x3d2bdb9072534a58), // 32
    f64::from_bits(0x3ff3200000000000),
    f64::from_bits(0xbfc6d60fe719d000),
    f64::from_bits(0xbd10e46aa3b2e266), // 33
    f64::from_bits(0x3ff3000000000000),
    f64::from_bits(0xbfc5ff3070a79000),
    f64::from_bits(0xbd1e9e439f105039), // 34
    f64::from_bits(0x3ff3000000000000),
    f64::from_bits(0xbfc5ff3070a79000),
    f64::from_bits(0xbd1e9e439f105039), // 35
    f64::from_bits(0x3ff2e00000000000),
    f64::from_bits(0xbfc526e5e3a1b000),
    f64::from_bits(0xbd20de8b90075b8f), // 36
    f64::from_bits(0x3ff2c00000000000),
    f64::from_bits(0xbfc44d2b6ccb8000),
    f64::from_bits(0x3d170cc16135783c), // 37
    f64::from_bits(0x3ff2c00000000000),
    f64::from_bits(0xbfc44d2b6ccb8000),
    f64::from_bits(0x3d170cc16135783c), // 38
    f64::from_bits(0x3ff2a00000000000),
    f64::from_bits(0xbfc371fc201e9000),
    f64::from_bits(0x3cf178864d27543a), // 39
    f64::from_bits(0x3ff2800000000000),
    f64::from_bits(0xbfc29552f81ff000),
    f64::from_bits(0xbd248d301771c408), // 40
    f64::from_bits(0x3ff2600000000000),
    f64::from_bits(0xbfc1b72ad52f6000),
    f64::from_bits(0xbd2e80a41811a396), // 41
    f64::from_bits(0x3ff2600000000000),
    f64::from_bits(0xbfc1b72ad52f6000),
    f64::from_bits(0xbd2e80a41811a396), // 42
    f64::from_bits(0x3ff2400000000000),
    f64::from_bits(0xbfc0d77e7cd09000),
    f64::from_bits(0x3d0a699688e85bf4), // 43
    f64::from_bits(0x3ff2400000000000),
    f64::from_bits(0xbfc0d77e7cd09000),
    f64::from_bits(0x3d0a699688e85bf4), // 44
    f64::from_bits(0x3ff2200000000000),
    f64::from_bits(0xbfbfec9131dbe000),
    f64::from_bits(0xbd2575545ca333f2), // 45
    f64::from_bits(0x3ff2000000000000),
    f64::from_bits(0xbfbe27076e2b0000),
    f64::from_bits(0x3d2a342c2af0003c), // 46
    f64::from_bits(0x3ff2000000000000),
    f64::from_bits(0xbfbe27076e2b0000),
    f64::from_bits(0x3d2a342c2af0003c), // 47
    f64::from_bits(0x3ff1e00000000000),
    f64::from_bits(0xbfbc5e548f5bc000),
    f64::from_bits(0xbd1d0c57585fbe06), // 48
    f64::from_bits(0x3ff1c00000000000),
    f64::from_bits(0xbfba926d3a4ae000),
    f64::from_bits(0x3d253935e85baac8), // 49
    f64::from_bits(0x3ff1c00000000000),
    f64::from_bits(0xbfba926d3a4ae000),
    f64::from_bits(0x3d253935e85baac8), // 50
    f64::from_bits(0x3ff1a00000000000),
    f64::from_bits(0xbfb8c345d631a000),
    f64::from_bits(0x3d137c294d2f5668), // 51
    f64::from_bits(0x3ff1a00000000000),
    f64::from_bits(0xbfb8c345d631a000),
    f64::from_bits(0x3d137c294d2f5668), // 52
    f64::from_bits(0x3ff1800000000000),
    f64::from_bits(0xbfb6f0d28ae56000),
    f64::from_bits(0xbd269737c93373da), // 53
    f64::from_bits(0x3ff1600000000000),
    f64::from_bits(0xbfb51b073f062000),
    f64::from_bits(0x3d1f025b61c65e57), // 54
    f64::from_bits(0x3ff1600000000000),
    f64::from_bits(0xbfb51b073f062000),
    f64::from_bits(0x3d1f025b61c65e57), // 55
    f64::from_bits(0x3ff1400000000000),
    f64::from_bits(0xbfb341d7961be000),
    f64::from_bits(0x3d2c5edaccf913df), // 56
    f64::from_bits(0x3ff1400000000000),
    f64::from_bits(0xbfb341d7961be000),
    f64::from_bits(0x3d2c5edaccf913df), // 57
    f64::from_bits(0x3ff1200000000000),
    f64::from_bits(0xbfb16536eea38000),
    f64::from_bits(0x3d147c5e768fa309), // 58
    f64::from_bits(0x3ff1000000000000),
    f64::from_bits(0xbfaf0a30c0118000),
    f64::from_bits(0x3d2d599e83368e91), // 59
    f64::from_bits(0x3ff1000000000000),
    f64::from_bits(0xbfaf0a30c0118000),
    f64::from_bits(0x3d2d599e83368e91), // 60
    f64::from_bits(0x3ff0e00000000000),
    f64::from_bits(0xbfab42dd71198000),
    f64::from_bits(0x3d1c827ae5d6704c), // 61
    f64::from_bits(0x3ff0e00000000000),
    f64::from_bits(0xbfab42dd71198000),
    f64::from_bits(0x3d1c827ae5d6704c), // 62
    f64::from_bits(0x3ff0c00000000000),
    f64::from_bits(0xbfa77458f632c000),
    f64::from_bits(0xbd2cfc4634f2a1ee), // 63
    f64::from_bits(0x3ff0c00000000000),
    f64::from_bits(0xbfa77458f632c000),
    f64::from_bits(0xbd2cfc4634f2a1ee), // 64
    f64::from_bits(0x3ff0a00000000000),
    f64::from_bits(0xbfa39e87b9fec000),
    f64::from_bits(0x3cf502b7f526feaa), // 65
    f64::from_bits(0x3ff0a00000000000),
    f64::from_bits(0xbfa39e87b9fec000),
    f64::from_bits(0x3cf502b7f526feaa), // 66
    f64::from_bits(0x3ff0800000000000),
    f64::from_bits(0xbf9f829b0e780000),
    f64::from_bits(0xbd2980267c7e09e4), // 67
    f64::from_bits(0x3ff0800000000000),
    f64::from_bits(0xbf9f829b0e780000),
    f64::from_bits(0xbd2980267c7e09e4), // 68
    f64::from_bits(0x3ff0600000000000),
    f64::from_bits(0xbf97b91b07d58000),
    f64::from_bits(0xbd288d5493faa639), // 69
    f64::from_bits(0x3ff0400000000000),
    f64::from_bits(0xbf8fc0a8b0fc0000),
    f64::from_bits(0xbcdf1e7cf6d3a69c), // 70
    f64::from_bits(0x3ff0400000000000),
    f64::from_bits(0xbf8fc0a8b0fc0000),
    f64::from_bits(0xbcdf1e7cf6d3a69c), // 71
    f64::from_bits(0x3ff0200000000000),
    f64::from_bits(0xbf7fe02a6b100000),
    f64::from_bits(0xbd19e23f0dda40e4), // 72
    f64::from_bits(0x3ff0200000000000),
    f64::from_bits(0xbf7fe02a6b100000),
    f64::from_bits(0xbd19e23f0dda40e4), // 73
    f64::from_bits(0x3ff0000000000000),
    f64::from_bits(0x0000000000000000),
    f64::from_bits(0x0000000000000000), // 74
    f64::from_bits(0x3ff0000000000000),
    f64::from_bits(0x0000000000000000),
    f64::from_bits(0x0000000000000000), // 75
    f64::from_bits(0x3fefc00000000000),
    f64::from_bits(0x3f80101575890000),
    f64::from_bits(0xbd10c76b999d2be8), // 76
    f64::from_bits(0x3fef800000000000),
    f64::from_bits(0x3f90205658938000),
    f64::from_bits(0xbd23dc5b06e2f7d2), // 77
    f64::from_bits(0x3fef400000000000),
    f64::from_bits(0x3f98492528c90000),
    f64::from_bits(0xbd2aa0ba325a0c34), // 78
    f64::from_bits(0x3fef000000000000),
    f64::from_bits(0x3fa0415d89e74000),
    f64::from_bits(0x3d0111c05cf1d753), // 79
    f64::from_bits(0x3feec00000000000),
    f64::from_bits(0x3fa466aed42e0000),
    f64::from_bits(0xbd2c167375bdfd28), // 80
    f64::from_bits(0x3fee800000000000),
    f64::from_bits(0x3fa894aa149fc000),
    f64::from_bits(0xbd197995d05a267d), // 81
    f64::from_bits(0x3fee400000000000),
    f64::from_bits(0x3faccb73cdddc000),
    f64::from_bits(0xbd1a68f247d82807), // 82
    f64::from_bits(0x3fee200000000000),
    f64::from_bits(0x3faeea31c006c000),
    f64::from_bits(0xbd0e113e4fc93b7b), // 83
    f64::from_bits(0x3fede00000000000),
    f64::from_bits(0x3fb1973bd1466000),
    f64::from_bits(0xbd25325d560d9e9b), // 84
    f64::from_bits(0x3feda00000000000),
    f64::from_bits(0x3fb3bdf5a7d1e000),
    f64::from_bits(0x3d2cc85ea5db4ed7), // 85
    f64::from_bits(0x3fed600000000000),
    f64::from_bits(0x3fb5e95a4d97a000),
    f64::from_bits(0xbd2c69063c5d1d1e), // 86
    f64::from_bits(0x3fed400000000000),
    f64::from_bits(0x3fb700d30aeac000),
    f64::from_bits(0x3cec1e8da99ded32), // 87
    f64::from_bits(0x3fed000000000000),
    f64::from_bits(0x3fb9335e5d594000),
    f64::from_bits(0x3d23115c3abd47da), // 88
    f64::from_bits(0x3fecc00000000000),
    f64::from_bits(0x3fbb6ac88dad6000),
    f64::from_bits(0xbd1390802bf768e5), // 89
    f64::from_bits(0x3feca00000000000),
    f64::from_bits(0x3fbc885801bc4000),
    f64::from_bits(0x3d2646d1c65aacd3), // 90
    f64::from_bits(0x3fec600000000000),
    f64::from_bits(0x3fbec739830a2000),
    f64::from_bits(0xbd2dc068afe645e0), // 91
    f64::from_bits(0x3fec400000000000),
    f64::from_bits(0x3fbfe89139dbe000),
    f64::from_bits(0xbd2534d64fa10afd), // 92
    f64::from_bits(0x3fec000000000000),
    f64::from_bits(0x3fc1178e8227e000),
    f64::from_bits(0x3d21ef78ce2d07f2), // 93
    f64::from_bits(0x3febe00000000000),
    f64::from_bits(0x3fc1aa2b7e23f000),
    f64::from_bits(0x3d2ca78e44389934), // 94
    f64::from_bits(0x3feba00000000000),
    f64::from_bits(0x3fc2d1610c868000),
    f64::from_bits(0x3d039d6ccb81b4a1), // 95
    f64::from_bits(0x3feb800000000000),
    f64::from_bits(0x3fc365fcb0159000),
    f64::from_bits(0x3cc62fa8234b7289), // 96
    f64::from_bits(0x3feb400000000000),
    f64::from_bits(0x3fc4913d8333b000),
    f64::from_bits(0x3d25837954fdb678), // 97
    f64::from_bits(0x3feb200000000000),
    f64::from_bits(0x3fc527e5e4a1b000),
    f64::from_bits(0x3d2633e8e5697dc7), // 98
    f64::from_bits(0x3feae00000000000),
    f64::from_bits(0x3fc6574ebe8c1000),
    f64::from_bits(0x3d19cf8b2c3c2e78), // 99
    f64::from_bits(0x3feac00000000000),
    f64::from_bits(0x3fc6f0128b757000),
    f64::from_bits(0xbd25118de59c21e1), // 100
    f64::from_bits(0x3feaa00000000000),
    f64::from_bits(0x3fc7898d85445000),
    f64::from_bits(0xbd1c661070914305), // 101
    f64::from_bits(0x3fea600000000000),
    f64::from_bits(0x3fc8beafeb390000),
    f64::from_bits(0xbd073d54aae92cd1), // 102
    f64::from_bits(0x3fea400000000000),
    f64::from_bits(0x3fc95a5adcf70000),
    f64::from_bits(0x3d07f22858a0ff6f), // 103
    f64::from_bits(0x3fea000000000000),
    f64::from_bits(0x3fca93ed3c8ae000),
    f64::from_bits(0xbd28724350562169), // 104
    f64::from_bits(0x3fe9e00000000000),
    f64::from_bits(0x3fcb31d8575bd000),
    f64::from_bits(0xbd0c358d4eace1aa), // 105
    f64::from_bits(0x3fe9c00000000000),
    f64::from_bits(0x3fcbd087383be000),
    f64::from_bits(0xbd2d4bc4595412b6), // 106
    f64::from_bits(0x3fe9a00000000000),
    f64::from_bits(0x3fcc6ffbc6f01000),
    f64::from_bits(0xbcf1ec72c5962bd2), // 107
    f64::from_bits(0x3fe9600000000000),
    f64::from_bits(0x3fcdb13db0d49000),
    f64::from_bits(0xbd2aff2af715b035), // 108
    f64::from_bits(0x3fe9400000000000),
    f64::from_bits(0x3fce530effe71000),
    f64::from_bits(0x3cc212276041f430), // 109
    f64::from_bits(0x3fe9200000000000),
    f64::from_bits(0x3fcef5ade4dd0000),
    f64::from_bits(0xbcca211565bb8e11), // 110
    f64::from_bits(0x3fe9000000000000),
    f64::from_bits(0x3fcf991c6cb3b000),
    f64::from_bits(0x3d1bcbecca0cdf30), // 111
    f64::from_bits(0x3fe8c00000000000),
    f64::from_bits(0x3fd07138604d5800),
    f64::from_bits(0x3cf89cdb16ed4e91), // 112
    f64::from_bits(0x3fe8a00000000000),
    f64::from_bits(0x3fd0c42d67616000),
    f64::from_bits(0x3d27188b163ceae9), // 113
    f64::from_bits(0x3fe8800000000000),
    f64::from_bits(0x3fd1178e8227e800),
    f64::from_bits(0xbd2c210e63a5f01c), // 114
    f64::from_bits(0x3fe8600000000000),
    f64::from_bits(0x3fd16b5ccbacf800),
    f64::from_bits(0x3d2b9acdf7a51681), // 115
    f64::from_bits(0x3fe8400000000000),
    f64::from_bits(0x3fd1bf99635a6800),
    f64::from_bits(0x3d2ca6ed5147bdb7), // 116
    f64::from_bits(0x3fe8200000000000),
    f64::from_bits(0x3fd214456d0eb800),
    f64::from_bits(0x3d0a87deba46baea), // 117
    f64::from_bits(0x3fe7e00000000000),
    f64::from_bits(0x3fd2bef07cdc9000),
    f64::from_bits(0x3d2a9cfa4a5004f4), // 118
    f64::from_bits(0x3fe7c00000000000),
    f64::from_bits(0x3fd314f1e1d36000),
    f64::from_bits(0xbd28e27ad3213cb8), // 119
    f64::from_bits(0x3fe7a00000000000),
    f64::from_bits(0x3fd36b6776be1000),
    f64::from_bits(0x3d116ecdb0f177c8), // 120
    f64::from_bits(0x3fe7800000000000),
    f64::from_bits(0x3fd3c25277333000),
    f64::from_bits(0x3d183b54b606bd5c), // 121
    f64::from_bits(0x3fe7600000000000),
    f64::from_bits(0x3fd419b423d5e800),
    f64::from_bits(0x3d08e436ec90e09d), // 122
    f64::from_bits(0x3fe7400000000000),
    f64::from_bits(0x3fd4718dc271c800),
    f64::from_bits(0xbd2f27ce0967d675), // 123
    f64::from_bits(0x3fe7200000000000),
    f64::from_bits(0x3fd4c9e09e173000),
    f64::from_bits(0xbd2e20891b0ad8a4), // 124
    f64::from_bits(0x3fe7000000000000),
    f64::from_bits(0x3fd522ae0738a000),
    f64::from_bits(0x3d2ebe708164c759), // 125
    f64::from_bits(0x3fe6e00000000000),
    f64::from_bits(0x3fd57bf753c8d000),
    f64::from_bits(0x3d1fadedee5d40ef), // 126
    f64::from_bits(0x3fe6c00000000000),
    f64::from_bits(0x3fd5d5bddf596000),
    f64::from_bits(0xbd0a0b2a08a465dc), // 127
];
